apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secret
  namespace: chatapp
type: Opaque
data:
  jwt: YWY5ZmU2MGZkOTFiYWI2YWE2NWNhNTQ1YTU4ZWViYjExY2Y1MmUwNGE2NGQyZjhjODY0YjBmNTQ5ZjExNDZiMWQyZDYwY2ViNTIwNGVhNjE5MWJiZWQzZTllZDI2NjczZjRmYzAyZWJlNjU4ZmMwZDgwYzg3N2I5ZGJjMjQ5MzMwOTNlYjQyMmZmNTcyMDdkODZiODVkMWEzZDdhY2FiODdkMGQzNGM3OWFiOGEyMDQ1MTAwZDhmYWU1YmNhMjRmNTIzMzUzNWNmNjY5OTQ5MGRmNTAxNTE5OTI1YWMxNjIzMmYxZGNhZmZhMzVlZWY3ZWE5Y2UxZDQwMWRiYzllYzcxMDU0ZTI0OWU2MzIwZTE3NzgyZWFhYzFkYjkxNWYwOWI0NjgwZWE1NjA0NWQ2ZDY1MWI0Njk3MzNlNzU4M2QxZDMxNzEzY2Q4NzY2ZTA5ZDRkZTViOGZhYzQxZjdmN2U0M2I1ZDg3MjFjYzhmM2M1ODhhNDRhYmYzYjQ2MWIyZTE5ZDk5OTRlNDhjOTA0YWY1MzEzZjVmOWMwNzY0YzViMjI1ZTQwOGY3OGQ4NWMzMGVjZmU3M2QwNjYzMDU5MmI4ZTUxMmU5MGVkMWE4YWU1ZWRmZTNmOWUwZmZmMjkxNjEwY2M5NWU4MDAzMTFiYTU3OTI4ZTgwM2NmZGRjYWY=
